## Data Acquisition & Summary Exercises

## 1.
Use the pydataset module to load the iris data set into a dataframe, df_iris

print the first 3 rows

print the number of rows and columns (shape)

print the column names

print the data type of each column

print the summary statistics for each of the numeric variables. Would you recommend rescaling the data based on these statistics?

In [110]:
import numpy as np
import pandas as pd
import seaborn as sns

In [131]:
import pydataset
pydataset.data('iris')
df_iris = pydataset.data('iris')

In [132]:
df_iris.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa

In [9]:
df_iris.shape

(150, 6)

In [138]:
df_iris.columns = [col.lower().replace('.', '_') for col in df_iris]

In [139]:
df_iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [140]:
df_iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [141]:
df_iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

#### data could be re-scaled if units were different or going to be put into regression model

## 2.
Read the data tab from the stats module dataset, Excel_Stats.xlsx, into a dataframe, df_excel

assign the first 100 rows to a new dataframe, df_excel_sample

print the number of rows of your original dataframe

print the first 5 column names

print the column names that have a data type of object

compute the range for each of the numeric variables.

In [144]:
# pd.read_excel('/Users/zach/codeup/cohorts/ada/Excel_Stats.xlsx', sheet_name='Data')

In [29]:
df_excel = pd.read_excel('Excel_Stats.xlsx', 'Data')

In [31]:
df_excel_sample = df_excel.head(100)
df_excel_sample

customer_id  gender  is_senior_citizen partner dependents  tenure  \
0   0002-ORFBO  Female                  0     Yes        Yes       9   
1   0003-MKNFE    Male                  0      No         No       9   
2   0004-TLHLJ    Male                  0      No         No       4   
3   0011-IGKFF    Male                  1     Yes         No      13   
4   0013-EXCHZ  Female                  1     Yes         No       3   
5   0013-MHZWF  Female                  0      No        Yes       9   
6   0013-SMEOE  Female                  1     Yes         No      71   
7   0014-BMAQU    Male                  0     Yes         No      63   
8   0015-UOCOJ  Female                  1      No         No       7   
9   0016-QLJIS  Female                  0     Yes        Yes      65   
10  0017-DINOC    Male                  0      No         No      54   
11  0017-IUDMW  Female                  0     Yes        Yes      72   
12  0018-NYROU  Female                  0     Yes         No       5   
13  0019-EFAEP  Female                  0      No         No      72   
14  0019-GFNTW  Female                  0      No         No      56   
15  0020-INWCK  Female                  0     Yes        Yes      71   
16  0020-JDNXP  Female                  0     Yes        Yes      34   
17  0021-IKXGC  Female                  1      No         No       1   
18  0022-TCJCI    Male                  1      No         No      45   
19  0023-HGHWL    Male                  1      No         No       1   
20  0023-UYUPN  Female                  1     Yes         No      50   
21  0023-XUOPT  Female                  0     Yes         No      13   
22  0027-KWYKW  Female                  0     Yes        Yes      23   
23  0030-FNXPP  Female                  0      No         No       3   
24  0031-PVLZI  Female                  0     Yes        Yes       4   
25  0032-PGELS  Female                  0     Yes        Yes       1   
26  0036-IHMOT  Female                  0     Yes        Yes      55   
27  0040-HALCW    Male                  0     Yes        Yes      54   
28  0042-JVWOJ    Male                  0      No         No      26   
29  0042-RLHYP  Female                  0     Yes        Yes      69   
..         ...     ...                ...     ...        ...     ...   
70  0114-RSRRW  Female                  0     Yes         No      10   
71  0115-TFERT    Male                  0     Yes         No      21   
72  0117-LFRMW    Male                  0     Yes        Yes      37   
73  0118-JPNOY  Female                  1      No         No      26   
74  0121-SNYRK    Male                  0      No         No      50   
75  0122-OAHPZ  Female                  0      No         No       7   
76  0123-CRBRT  Female                  0     Yes        Yes      61   
77  0125-LZQXK    Male                  0      No         No      15   
78  0128-MKWSG  Female                  0      No        Yes      26   
79  0129-KPTWJ    Male                  0     Yes         No      72   
80  0129-QMPDR    Male                  0     Yes        Yes      44   
81  0130-SXOUN    Male                  0      No         No      66   
82  0133-BMFZO  Female                  0      No         No       2   
83  0134-XWXCE  Female                  1      No         No      44   
84  0135-NMXAP  Female                  0      No         No      12   
85  0136-IFMYD    Male                  1     Yes         No      69   
86  0137-OCGAB  Female                  0      No         No       1   
87  0137-UDEUO  Female                  0      No         No       3   
88  0139-IVFJG  Female                  0     Yes         No       2   
89  0141-YEAYS  Female                  1      No         No      27   
90  0142-GVYSN    Male                  0      No         No      26   
91  0147-ESWWR  Female                  1     Yes         No      39   
92  0148-DCDOS    Male                  0      No         No      25   
93  0151-ONTOV  Female                  0  

In [35]:
df_excel.shape[0]

7043

In [47]:
df_excel.columns[0:5]

Index(['customer_id', 'gender', 'is_senior_citizen', 'partner', 'dependents'], dtype='object')

In [56]:
df_excel.dtypes

customer_id           object
gender                object
is_senior_citizen      int64
partner               object
dependents            object
tenure                 int64
phone_service          int64
internet_service       int64
contract_type          int64
payment_type          object
monthly_charges      float64
total_charges        float64
churn                 object
dtype: object

In [55]:
df_excel.select_dtypes(['object']).columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

In [147]:
df_excel.select_dtypes('number').columns

Index(['is_senior_citizen', 'tenure', 'phone_service', 'internet_service',
       'contract_type', 'monthly_charges', 'total_charges'],
      dtype='object')

In [151]:
for col in df_excel[df_excel.select_dtypes('number').columns]:
    r = df_excel[col].max() - df_excel[col].min()
    print(f'{col}: {r}')

is_senior_citizen: 1
tenure: 72
phone_service: 2
internet_service: 2
contract_type: 2
monthly_charges: 100.5
total_charges: 8666.0


In [154]:
#OR:
df_excel[df_excel.select_dtypes('number').columns].apply(lambda s: s.max() - s.min())

is_senior_citizen       1.0
tenure                 72.0
phone_service           2.0
internet_service        2.0
contract_type           2.0
monthly_charges       100.5
total_charges        8666.0
dtype: float64

## 3.
Read train.csv from google drive (shared through classroom in topic 'Classification') into a dataframe labeled df_google

print the first 3 rows

print the number of rows and columns

print the column names

print the data type of each column

print the summary statistics for each of the numeric variables

print the unique values for each of your categorical variables

In [75]:
df_google = pd.read_csv('train.csv')

In [76]:
df_google.head(3)

rowid                 date  Temperature  Humidity  Light     CO2  \
0      1  2015-02-04 17:51:00        23.18   27.2720  426.0  721.25   
1      2  2015-02-04 17:51:59        23.15   27.2675  429.5  714.00   
2      3  2015-02-04 17:53:00        23.15   27.2450  426.0  713.50   

   HumidityRatio  Occupancy  
0       0.004793          1  
1       0.004783          1  
2       0.004779          1

In [78]:
df_google.shape

(8143, 8)

In [79]:
df_google.columns

Index(['rowid', 'date', 'Temperature', 'Humidity', 'Light', 'CO2',
       'HumidityRatio', 'Occupancy'],
      dtype='object')

In [80]:
df_google.dtypes

rowid              int64
date              object
Temperature      float64
Humidity         float64
Light            float64
CO2              float64
HumidityRatio    float64
Occupancy          int64
dtype: object

In [81]:
df_google.describe()

rowid  Temperature     Humidity        Light          CO2  \
count  8143.000000  8143.000000  8143.000000  8143.000000  8143.000000   
mean   4072.000000    20.619084    25.731507   119.519375   606.546243   
std    2350.825954     1.016916     5.531211   194.755805   314.320877   
min       1.000000    19.000000    16.745000     0.000000   412.750000   
25%    2036.500000    19.700000    20.200000     0.000000   439.000000   
50%    4072.000000    20.390000    26.222500     0.000000   453.500000   
75%    6107.500000    21.390000    30.533333   256.375000   638.833333   
max    8143.000000    23.180000    39.117500  1546.333333  2028.500000   

       HumidityRatio    Occupancy  
count    8143.000000  8143.000000  
mean        0.003863     0.212330  
std         0.000852     0.408982  
min         0.002674     0.000000  
25%         0.003078     0.000000  
50%         0.003801     0.000000  
75%         0.004352     0.000000  
max         0.006476     1.000000

In [156]:
df_google.Occupancy.unique()

array([1, 0])

## 4.
In mysql workbench or a terminal, write a query to select all the columns of the passengers table from the titanic database. Export that table to a csv you store locally. Read that csv into a dataframe df_csv.

print the head and tail of your new dataframe

print the number of rows and columns

print the column names

print the data type of each column

print the summary statistics for each numeric variable

print the unique values for each categorical variables. If there are more than 5 distince values, print the top 5 in terms of prevelence or frequency.

In [ ]:
# import env
# url = f'mysql+pymysql://{env.username}:{env.password}@{env.hostname}/titanic_db'
# df = pd.read_sql('SELECT * FROM passengers', url)

In [88]:
df_csv = pd.read_csv('titanic_passengers.csv')

In [ ]:
# pd.concat([df.head(), df.tail()])

In [89]:
df_csv.head()

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   

  embarked  class deck  embark_town  alone  
0        S  Third  NaN  Southampton      0  
1        C  First    C    Cherbourg      0  
2        S  Third  NaN  Southampton      1  
3        S  First    C  Southampton      0  
4        S  Third  NaN  Southampton      1

In [90]:
df_csv.tail()

passenger_id  survived  pclass     sex   age  sibsp  parch   fare  \
886           886         0       2    male  27.0      0      0  13.00   
887           887         1       1  female  19.0      0      0  30.00   
888           888         0       3  female   NaN      1      2  23.45   
889           889         1       1    male  26.0      0      0  30.00   
890           890         0       3    male  32.0      0      0   7.75   

    embarked   class deck  embark_town  alone  
886        S  Second  NaN  Southampton      1  
887        S   First    B  Southampton      1  
888        S   Third  NaN  Southampton      0  
889        C   First    C    Cherbourg      1  
890        Q   Third  NaN   Queenstown      1

In [91]:
df_csv.shape

(891, 13)

In [92]:
df_csv.columns

Index(['passenger_id', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch',
       'fare', 'embarked', 'class', 'deck', 'embark_town', 'alone'],
      dtype='object')

In [93]:
df_csv.dtypes

passenger_id      int64
survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class            object
deck             object
embark_town      object
alone             int64
dtype: object

In [94]:
df_csv.describe()

passenger_id    survived      pclass         age       sibsp  \
count    891.000000  891.000000  891.000000  714.000000  891.000000   
mean     445.000000    0.383838    2.308642   29.699118    0.523008   
std      257.353842    0.486592    0.836071   14.526497    1.102743   
min        0.000000    0.000000    1.000000    0.420000    0.000000   
25%      222.500000    0.000000    2.000000   20.125000    0.000000   
50%      445.000000    0.000000    3.000000   28.000000    0.000000   
75%      667.500000    1.000000    3.000000   38.000000    1.000000   
max      890.000000    1.000000    3.000000   80.000000    8.000000   

            parch        fare       alone  
count  891.000000  891.000000  891.000000  
mean     0.381594   32.204208    0.602694  
std      0.806057   49.693429    0.489615  
min      0.000000    0.000000    0.000000  
25%      0.000000    7.910400    0.000000  
50%      0.000000   14.454200    1.000000  
75%      0.000000   31.000000    1.000000  
max      6.000000  512.329200    1.000000

In [142]:
for column_name in df_csv:
        print(df_csv[column_name].head().unique())

[0 1 2 3 4]
[0 1]
[3 1]
['male' 'female']
[22. 38. 26. 35.]
[1 0]
[0]
[ 7.25   71.2833  7.925  53.1     8.05  ]
['S' 'C']
['Third' 'First']
[nan 'C']
['Southampton' 'Cherbourg']
[0 1]


In [157]:
df_csv.sex.unique()

array(['male', 'female'], dtype=object)

In [158]:
df_csv.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [161]:
df_csv['class'].unique()

array(['Third', 'First', 'Second'], dtype=object)

In [162]:
df_csv.deck.unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F'], dtype=object)

In [164]:
df_csv.embark_town.unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [165]:
# for col in cols:
#     print(f"{col:>10}: {', '.join(pd.Series(df[col].value_counts().index.values).astype(str).unique()[:5])}")

In [ ]:
# tit_obj = df_csv.select_dtypes(object)
# for col in tit_obj:
#     print(col, (df_csv[col].unique()[:5]))

In [ ]:
# {col: list(df[col].unique())[:5] for col in df.select_dtypes(object)}